config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  namespace :admin do
    resources :dashboard, only: [:index]
    resources :events, only: [:new, :create, :edit, :update, :destroy]
    resources :venues, param: :name, only: [:edit, :update, :create, :destroy]
  end
  resources :cart_events, only: [:create, :update, :destroy]
  resources :cart, only: [:index]
  resources :events, only: [:index] do
    get 'occurred', on: :collection
  end
  resources :users, only: [:new, :create, :edit, :update]
  resources :orders, only: [:index, :create, :show]
  resources :charges
  resources :venues, only: [:index, :new, :create]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/dashboard', to: 'users#show'
  get '/categories/:title', to: 'categories#show', as: :category
  get '/auth/twitter', as: :twitter_login
  get '/auth/twitter/callback', to: 'sessions#create'
  get '/:name', to: 'venues#show', as: :venue
  get '/:name/:title', to: 'events#show', as: :event
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(contents)
    @contents = contents || {}
  end

  def add_event(event_id)
    @contents[event_id.to_s] ||= 0
    @contents[event_id.to_s] += 1
  end

  def total_tickets
    contents.values.sum
  end

  def total_cost
    if contents.empty?
      0.00
    elsif contents.values.max < 2
      Event.find(contents.keys).pluck(:price).sum
    else
      process_sum
    end
  end

  def all_events
    contents.map do |event_id, quantity|
      CartEvent.new(event_id, quantity)
    end
  end

  private

  def process_sum
    all_events.reduce(0) do |initial, event|
      initial += event.sub_total
    end
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    @events = @cart.all_events
  end
end

app/views/cart/index.html.erb
<div class="page-content">
  <h1><strong>Shopping Cart</strong></h1>
  <div class="table-responsive">
    <% if @events.empty? %>
      <div class="well" id="no-pending-msg">
        <center><h4>
          <strong>Your cart is empty!</strong>
          <br><br />
          Time to make some memories at one of the many incredible <%= link_to "events", events_path %> coming soon!
        </h4></center>
      </div>
    <% else %>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Event Name</th>
            <th>Category</th>
            <th>Venue</th>
            <th>Date</th>
            <th>Quantity</th>
            <th>Unit Price</th>
            <th>Subtotal</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |event| %>
            <tr id="event-<%= event.id %>">
              <td><%= image_tag event.venue.image_path, class: "cart-pic img-circle" %></td>
              <td><%= link_to event.title, event_path(event.venue, event) %></td>
              <td><%= event.category.title %></td>
              <td><%= event.venue.name %></td>
              <td><%= event.event_date %></td>
              <td>
                <%= form_for(event, url: cart_event_path(event)) do |f| %>
                  <div class='form-group'>
                    <%= f.select :quantity, quantities, {}, { value: event.quantity, class: 'form-control', onchange: 'this.form.submit();' } %>
                  </div>
                <% end %>
              </td>
              <td><%= number_to_currency(event.price) %></td>
              <td><%= number_to_currency(event.sub_total) %></td>
              <td><%= button_to "Remove", cart_event_path(event), method: :delete, class: 'btn btn-danger btn-sm' %></td>
            </tr>
          <% end %>
          <tr>
            <td colspan='9' class='text-right'>
              <strong>Total: <%= number_to_currency(@cart.total_cost) %></strong>
            </td>
          </tr>
        </tbody>
      </table>
    <% end %>
  </div>
  <div class='col-md-12'>
    <%= link_to 'Back to All Events', events_path, class: 'col-md-2 btn btn-default' %>
    <% unless @cart.contents.empty? %>
      <% if current_user %>
        <%= link_to 'Checkout', orders_path, method: :post, class: 'col-md-2 col-md-offset-8 btn btn-primary' %>
      <% else %>
        <%= link_to 'Login or Create Account to Checkout', login_path, class: 'col-md-3 col-md-offset-7 btn btn-info' %>
      <% end %>
    <% end %>
  </div>
</div>