config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  namespace :admin do
    resources :dashboard, only: [:index]
    resources :events, only: [:new, :create, :edit, :update, :destroy]
    resources :venues, param: :name, only: [:edit, :update, :create, :destroy]
  end
  resources :cart_events, only: [:create, :update, :destroy]
  resources :cart, only: [:index]
  resources :events, only: [:index] do
    get 'occurred', on: :collection
  end
  resources :users, only: [:new, :create, :edit, :update]
  resources :orders, only: [:index, :create, :show]
  resources :charges
  resources :venues, only: [:index, :new, :create]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/dashboard', to: 'users#show'
  get '/categories/:title', to: 'categories#show', as: :category
  get '/auth/twitter', as: :twitter_login
  get '/auth/twitter/callback', to: 'sessions#create'
  get '/:name', to: 'venues#show', as: :venue
  get '/:name/:title', to: 'events#show', as: :event
end

app/views/shared/_dashboard.html.erb
<div class="well center" id="dashboard">
  <div class="well col-md-10 col-md-offset-1">
    <table class="table" id="user_dashboard">
      <tr>
        <th>Username</th>
        <td><%= current_user.username %></td>
      </tr>
      <tr>
        <th>E-mail</th>
        <td><%= current_user.email %></td>
      </tr>
      <tr>
        <th>Date Registered</th>
        <td><%= current_user.date_registered %></td>
      </tr>
      <% if venue_admin_only? %>
        <tr>
          <th>Venue</th>
          <td><%= @venue.name %><%= link_to 'Manage Venue', edit_admin_venue_path(name: @venue.slug), class: 'btn btn-sm btn-default pull-right' %></td>
        </tr>
      <% end %>
      <tr>
        <th>Orders Placed</th>
        <td><%= current_user.orders.count %><%= link_to 'View My Orders', orders_path, class: 'btn btn-sm btn-default pull-right' %></td>
      </tr>
    </table>
      <center><%= link_to 'Manage My Account', edit_user_path(current_user), class: 'btn btn-default' %></center>
      <center><%= link_to 'Manage Events', venue_path(name: @venue.slug), class: 'btn btn-default top-margin' if venue_admin_only? %></center>
      <% if platform_admin? %>
        <br />
        <center>
          <%= link_to 'Manage Events', events_path, class: 'btn btn-default top-margin' %>
          <%= link_to 'Manage Venues', venues_path, class: 'btn btn-default top-margin' %>
        </center>
      <% end %>
  </div>

  <% if !venue_admin? && venue_exists? %>
    <div class="well col-md-8 col-md-offset-2">
      <center>
        <strong>Thank you for choosing to become a certified seller at Nosebleed Tix!</strong>
        <br><br />
        <p><small>If you have submitted an application within the last 7 days, please be patient as we process your request.</small></p>
        <p><small>If you are an existing vendor who is having trouble with your account or have any questions for the Nosebleed staff, please contact us <%= mail_to "nosebleedtix@gmail.com", "here" %>.</small></p>
      </center>
    </div>
  <% elsif !venue_admin? && !venue_exists? %>
    <div class="sell-btn">
      <%= link_to "Sell With Us", new_venue_path, class: "btn btn-lg btn-primary shadow" %>
    </div>
  <% else %>
  <% end %>

  <% if platform_admin? %>
    <div class="well col-md-10 col-md-offset-1 table-responsive" id="pending">
      <h2>Pending Venues</h2>
      <% if @venues.empty? %>
        <div id="no-pending-msg">
          <center><h4><em>There are no venues currently pending. Get out there and recruit!</em></h4></center>
        </div>
      <% else %>
        <table class="table">
          <thead>
            <th>Venue Name</th>
            <th>Location</th>
            <th>Capacity</th>
            <th>Admin</th>
            <th class="text-center col-md-2" colspan="2">Action</th>
          </thead>
          <tbody>
            <% @venues.each do |venue| %>
            <tr id="venue-<%= venue.id %>">
              <td><%= venue.name %></td>
              <td><%= venue.location %></td>
              <td><%= venue.capacity %></td>
              <td><%= venue.admin.username %></td>
              <td>
                <%= button_to "Approve", admin_venues_path, { params: { name: venue.slug }, class: "btn btn-success center_button btn-xs" } %>
              </td>
              <td>
                <%= button_to "Decline", admin_venue_path(venue), { method: :delete, class: "btn btn-danger center_button btn-xs" } %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_event_form.html.erb
<div class="well center-form">
  <%= form_for(@event, url: path) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :supporting_act, "Supporting Act" %>
      <%= f.text_field :supporting_act, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :date %>
      <%= f.date_field :date, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, min: 0, step: 0.01, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :category_id %>
      <%= f.select :category_id, event_categories, {}, class: 'form-control' %>
    </div>
    <% if platform_admin? %>
      <div class="form-group">
        <%= f.label :venue_id %>
        <%= f.select :venue_id, event_venues, {}, class: 'form-control' %>
      </div>
    <% end %>
    <%= f.submit "#{button}", class: 'btn btn-success' %>
    <% if request.referrer %>
      <%= link_to "Cancel", request.referrer, class: 'btn btn-primary' %>
    <% else %>
      <%= link_to "Cancel", admin_dashboard_index_path, class: 'btn btn-primary' %>
    <% end %>
  <% end %>
</div>

app/views/shared/_event_list.html.erb
<div id="events_list">
  <div class="well col-md-10 padded">
    <div class="table-responsive col-md-8 fit-width">
      <table class="table">
        <thead>
          <tr>
            <th>Event</th>
            <th>Supporting Act</th>
            <th>Venue</th>
            <th>Category</th>
            <th>Location</th>
            <th>Date</th>
            <th>Price</th>
            <th class="text-center">Purchase</th>
            <% if venue_admin? %>
              <th class="text-center">Edit</th>
              <th class="text-center">Delete</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |event| %>
            <tr class="event" id="event-<%= event.id %>" data-all="<%= event.title %> <%= event.venue_name %> <%= event.category.title %> <%= event.supporting_act %> <%= event.venue_location %> <%= event.event_date %>">
              <td><%= link_to event.title, event_path(event.venue, event) %></td>
              <td><%= event.supporting_act %></td>
              <td><%= link_to event.venue_name, venue_path(event.venue) %></td>
              <td><%= link_to event.category.title, category_path(event.category) %></td>
              <td><%= event.venue_location %></td>
              <td><%= event.event_date %></td>
              <td><%= number_to_currency(event.price) %></td>
              <td>
                <%= button_to "#{btn_label}", cart_events_path(event_id: event.id), class: "center_button btn btn-#{btn_class}", disabled: status %>
              </td>
              <% if platform_admin? || event.venue == current_admins_venue %>
                <td>
                  <%= link_to 'Edit', edit_admin_event_path(event), class: 'center_button btn btn-sm btn-default' %>
                </td>
                <td>
                  <%= button_to "Delete", admin_event_path(event), method: :delete, class: 'center_button btn btn-sm btn-danger' %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/shared/_login_form.html.erb
<div class="well">
  <%= form_for(target, url: path) do |f|  %>
    <p>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </p>
    <% unless login_path? %>
    <p>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </p>
    <% end %>
    <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </p>
    <% if request.referrer %>
      <%= link_to "Cancel", request.referrer, class: "btn btn-primary top-margin" %>
    <% else %>
      <%= link_to "Cancel", root_path, class: "btn btn-primary top-margin" %>
    <% end %>
    <%= f.submit button, class: "btn btn-#{btn_class} top-margin"%>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top" id="topnavbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapsingnav">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to image_tag('logo-big.png', class: 'logo'), root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="collapsingnav">
      <% if current_user %>
        <ul class="nav navbar-nav" id="current-user-info">
          Logged in as <%= current_user.username %><br>(<%= link_to "View Profile", dashboard_path %>)
        </ul>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to venues_path do %>
            <i class="fa fa-building"></i> Venues
          <% end %>
        </li>
        <li>
          <%= link_to events_path do %>
            <i class="fa fa-align-justify"></i> All Events
          <% end %>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% categories.each do |category| %>
              <li><%= link_to "#{category.title}", category_path(category) %></li>
            <% end %>
          </ul>
        </li>
        <li>
          <%= mail_to "nosebleedtix@gmail.com" do %>
            <i class="fa fa-envelope"></i> Email Us
          <% end %>
        </li>
        <li>
          <%= link_to cart_index_path do %>
            <i class="fa fa-shopping-cart"></i> Cart: <%= @cart.total_tickets %>
          <% end %>
        </li>
        <% if current_user %>
          <li><%= link_to logout_path, method: :delete do %>
            <i class="fa fa-sign-out"></i> Logout
          <% end %></li>
        <% else %>
          <li><%= link_to login_path do %>
            <i class="fa fa-sign-in"></i> Login
          <% end %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_venue_form.html.erb
<div class="well center-form">
  <%= form_for(@venue, url: path, html: {multipart: true}) do |f| %>
    <div class="form-group">
      <%= f.label :name, 'Venue Name' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :state %>
      <%= f.text_field :state, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :capacity %>
      <%= f.number_field :capacity, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :upload_image, 'Image' %>
      <%= f.file_field :upload_image, class: 'center_button' %>
    </div>
    <%= f.hidden_field :status, value: 'offline' %>
    <%= f.submit label, class: 'btn btn-success top-margin' %>
    <% if platform_admin? && request.referrer %>
      <%= link_to "Cancel", request.referrer, class: 'btn btn-primary top-margin' %>
    <% else %>
      <%= link_to "Cancel", cancel_path, class: 'btn btn-primary top-margin' %>
    <% end %>
  <% end %>
</div>