config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  namespace :admin do
    resources :dashboard, only: [:index]
    resources :events, only: [:new, :create, :edit, :update, :destroy]
    resources :venues, param: :name, only: [:edit, :update, :create, :destroy]
  end
  resources :cart_events, only: [:create, :update, :destroy]
  resources :cart, only: [:index]
  resources :events, only: [:index] do
    get 'occurred', on: :collection
  end
  resources :users, only: [:new, :create, :edit, :update]
  resources :orders, only: [:index, :create, :show]
  resources :charges
  resources :venues, only: [:index, :new, :create]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/dashboard', to: 'users#show'
  get '/categories/:title', to: 'categories#show', as: :category
  get '/auth/twitter', as: :twitter_login
  get '/auth/twitter/callback', to: 'sessions#create'
  get '/:name', to: 'venues#show', as: :venue
  get '/:name/:title', to: 'events#show', as: :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :category
  belongs_to :venue
  has_many :order_events
  has_many :orders, through: :order_events
  validates :title, presence: true, uniqueness: { scope: [:venue_id, :date] }
  validates :price, presence: true, :numericality => {:greater_than => 0}
  validates :category, presence: true
  validates :venue, presence: true
  validates :slug, presence: true, uniqueness: { case_sensitive: false }
  before_validation :create_slug

  enum status: %w(upcoming occurred)

  def venue_name
    venue.name
  end

  def venue_location
    venue.location
  end

  def past_event?
    status == 'occurred'
  end

  def to_param
    slug
  end

  def event_date
    date.strftime("%m-%d-%Y")
  end

  private

  def create_slug
    self.slug = "#{title.parameterize}-#{event_date}" if title
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :set_event, only: [:edit, :update, :destroy]
  before_action :verify_permissions, only: [:edit]

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params_with_venue)
    if @event.save
      flash[:success] = 'Event Added Successfully!'
      redirect_to event_path(@event.venue, @event)
    else
      flash.now[:danger] = @event.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update_attributes(params_with_venue)
      flash[:success] = "Event Updated Successfully!"
      redirect_to event_path(@event.venue, @event)
    else
      flash.now[:danger] = @event.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    @event.destroy
    flash[:success] = "Event Removed Successfully!"
    if current_user.platform_admin?
      redirect_to events_path
    else
      redirect_to venue_path(@event.venue)
    end
  end

  private

  def event_params
    params.require(:event).permit(:title,
                                  :supporting_act,
                                  :price,
                                  :date,
                                  :category_id,
                                  :venue_id,
                                  :upload_image)
  end

  def params_with_venue
    return event_params if current_user.platform_admin?
    form_params = event_params
    form_params[:venue_id] = current_admins_venue.id
    form_params
  end

  def set_event
    @event = Event.find_by_slug(params[:id])
  end

  def verify_permissions
    unless current_user.platform_admin? ||
           @event.venue.admin == current_admins_venue.admin
      render_404
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.where(status: 0)
  end

  def unavailable
    @events = Event.where(status: 1)
  end

  def show
    @event = Event.find_by_slug(params[:title])
    venue = Venue.find_by_slug(params[:name])
    if @event.nil? || venue.nil?
      render_404
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_venues
    Venue.all.map { |venue| [venue.name, venue.id] }
  end

  def event_categories
    Category.all.map { |category| [category.title, category.id] }
  end
end

app/views/events/_filter.html.erb
<div class="filter filter-bar btn btn-warning">
  <label>Search&nbsp;</label>
  <%= text_field :event, :filter_all, class: "filter-field" %>
</div>

app/views/events/index.html.erb
<div class="page-content">
  <h1><strong>All Events</strong></h1>
  <center><%= render partial: "filter" %></center>
  <center><% if venue_admin? %>
    <%= link_to 'Back', request.referrer, class: 'btn btn-md btn-primary' if platform_admin? && request.referrer %>
    <%= link_to 'Add New Event', new_admin_event_path, class: 'btn btn-lg btn-success' %>
  <% end %></center>

  <%= render partial: 'shared/event_list', locals: { btn_label: 'Add to Cart', btn_class: 'primary btn-sm', status: false} %>
</div>

app/views/events/show.html.erb
<div class="event-show">
  <div class="well col-md-10 padded">
    <h1><%= @event.title %></h1>
    <%= image_tag(@event.venue.image_path, alt: "#{@event.title} pic", class: 'img-thumbnail show-image', style: 'float:left') %>
    <div class="event-content">
      <h2><p><strong>Venue:</strong> <%= @event.venue_name %></h2></p>
      <h4><p><strong>Category:</strong> <%= @event.category.title %></p></h4>
      <h4><p><strong>Featuring:</strong> <%= @event.supporting_act %></p></h4>
      <h4><p><strong>Date:</strong> <%= @event.event_date %></p></h4>
      <br />
      <p><em>See the sights and hear the sounds at <%= @event.title %>, featuring <%= @event.supporting_act %>. Sure to be an unforgettable evening!</em></p>
      <br />
      <p><strong>Get your tickets for some truly believable seats now!</strong></p>
      <h4><p><strong><%= number_to_currency(@event.price) %></strong></p></h4>
      <% if @event.past_event? %>
        <p><%= link_to 'SOLD OUT', cart_events_path(event_id: @event.id), class: 'center_button btn btn-danger', disabled: 'disabled' %></p>
      <% else %>
        <p><%= button_to 'Add to Cart', cart_events_path(event_id: @event.id), class: 'center_button btn btn-primary' %></p>
        <br />
        <% if platform_admin? || @event.venue == current_admins_venue %>
          <p>
            <%= link_to 'Edit', edit_admin_event_path(@event), class: 'btn btn-default' %>
            <%= link_to "Delete", admin_event_path(@event), method: :delete, class: 'btn btn-sm btn-danger' %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>